---
title: "Heuristic"
format: html
editor: source
---

```{r message = F}
library(targets)
library(igraph)
library(tidyverse)
library(here)
tar_config_set(
  script = here::here('_targets.R'),
  store = here::here('_targets')
)
theme_set(theme_classic())
source(here::here("R/functions.R"))
```

## Load data

```{r}
tar_load(timewindows_heuristic)
tar_load(timewindows)
tar_load(graphs_flight_heuristic)
tar_load(graphs_feeding_heuristic)
tar_load(graphs_flight)
tar_load(graphs_feeding)
```

```{r}
fl_density <- map(graphs_flight_heuristic, ~map_dbl(.x, ~igraph::edge_density(nonzero(.x))))
fe_density <- map(graphs_feeding_heuristic, ~map_dbl(.x, ~igraph::edge_density(nonzero(.x))))

fl_density_orig <- map(graphs_flight, ~map_dbl(.x, ~igraph::edge_density(nonzero(.x))))
fe_density_orig <- map(graphs_feeding, ~map_dbl(.x, ~igraph::edge_density(nonzero(.x))))
```

Get measures

```{r}
getmeasures <- function(dens, tw, sitch){
  out <- map2(.x = dens, .y = tw,
              ~data.frame(dens = .x, 
                          w = .y, 
                          situ = sitch) %>%
                mutate(step = 1:n(),
                       time = step*w))
  return(out)
}
measures_fl <- getmeasures(fl_density, timewindows_heuristic, "flight")
measures_fe <- getmeasures(fe_density, timewindows_heuristic, "feeding")

all <- list(measures_fl, measures_fe)
all <- map(all, list_rbind)

measures <- do.call(rbind, all) %>%
  rename("density" = dens) %>%
  arrange(situ, w)
```

Now let's plot the CV (sd/mean)

```{r}
cvs <- measures %>%
  group_by(w, situ) %>%
  summarize(mn = mean(density, na.rm = T),
            sd = sd(density, na.rm = T),
            cv = sd/mn,
            var = var(density)) %>%
  ungroup() %>%
  mutate(w_days = w)
```

```{r}
## Density only, since that's most directly comparable to Caceres et al.
cvs %>%
  ggplot(aes(x = w_days, y = cv, col = situ))+
  geom_line()+
  geom_point()+
  ylab("CV")+
  xlab("Time window (days)")+
  scale_color_manual(name = "Situation", values = situcolors[1:2])+
  theme(legend.position = "bottom",
        text = element_text(size = 16))
cvs_fig
ggsave(cvs_fig, file = here("fig/cvs_lines.png"), width = 6, height = 4)

var_fig <- cvs %>%
  ggplot(aes(x = w_days, y = var, col = situ))+
  geom_line(linewidth = 2, alpha = 1)+
  #geom_point(size = 2, alpha = 0.7)+
  ylab("Var(Density)")+
  xlab("Time window (days)")+
  scale_color_manual(name = "Situation", values = situcolors[1:2])+
  theme(legend.position = "bottom",
        text = element_text(size = 16))+
  guides(color = guide_legend(override.aes = 
                                list(linewidth = 2, size = 3, alpha = 1)))
var_fig

sd_fig <- cvs %>%
  ggplot(aes(x = w_days, y = sd, col = situ))+
  geom_line(linewidth = 2, alpha = 1)+
  #geom_point(size = 2, alpha = 0.7)+
  ylab("SD(Density)")+
  xlab("Time window (days)")+
  scale_color_manual(name = "Situation", values = situcolors[1:2])+
  theme(legend.position = "bottom",
        text = element_text(size = 16))+
  guides(color = guide_legend(override.aes = 
                                list(linewidth = 2, size = 3, alpha = 1)))
sd_fig
```

```{r}
## Look at the time series at various scales
measures %>%
  filter(w %in% c(1, 5, 10, 25)) %>%
  ggplot(aes(x = time, y = density, col = situ))+
  geom_line(aes(linewidth = situ, alpha = situ))+
  facet_wrap(~w, scales = "free_y")+
  scale_color_manual(name = "Situation", values = situcolors[1:2])+
  scale_linewidth_manual(values = c(0.5, 1, 0.5, 0.5))+
  scale_alpha_manual(values = c(0.5, 1, 0.5, 0.5))+
  guides(linewidth = "none", alpha = "none",
         color = guide_legend(override.aes = 
                                list(linewidth = 3, alpha = 1)))+
  ylab("Density")+
  xlab("Time")+
  theme(legend.position = "bottom",
        text = element_text(size = 16))

density_over_time <- measures %>%
  filter(w %in% c(1, 5, 10, 25), situ %in% c("feeding", "flight")) %>%
  ggplot(aes(x = time, y = density, col = situ))+
  geom_line(aes(linewidth = situ, alpha = situ), linewidth = 1, alpha = 1)+
  scale_color_manual(values = situcolors[1:2])+
  facet_wrap(~w, scales = "free")+
  guides(linewidth = "none", alpha = "none",
         color = guide_legend(override.aes = 
                                list(linewidth = 3, alpha = 1)))+
  ylab("Density")+
  xlab("Time")+
  scale_y_continuous(limits =c(0, 0.8), breaks = seq(from = 0, to = 0.8, by = 0.2))+
  scale_x_continuous(limits = c(0, 130), breaks = seq(from = 0, to = 130, by = 25))+
  theme(legend.position = "bottom",
        text = element_text(size = 16),
        strip.text = element_blank(),
        strip.background = element_blank(),
        axis.text = element_text(size = 12))
density_over_time

ggsave(density_over_time, file = here("fig/density_over_time.png"), width = 6, height = 4)
```
